### ISSUE TITLE
No grandmaster info for archon mode

### ISSUE THREAD

**Issue by Xeizzeth** [BurnySc2/MMR-Ranges#3]
It is possible to get into grandmaster while playing archon mode, yet no info regarding this is shown by the website of this repo.

**Comment by BurnySc2** [comment]
Thanks for the suggestion but I don't really want to support that.

At the moment it takes 3600 MMR on EU to get into Archon GM, yet the Diamond 1 requirement starts at 3587 MMR.

With 1v1 GM, I wanted to highlight at what MMR you can get into GM (e.g. 4800 to 5500 on EU is Master 1 atm) - while the overlap for Archon mode is too weird.
