### ISSUE TITLE
How often is the data updated?

### ISSUE THREAD

**Issue by Xefise** [BurnySc2/MMR-Ranges#5]
How often is the data updated? The data update is not automated?

**Comment by BurnySc2** [comment]
It is updated twice per day, but the SC2 API has been down / incomplete since feb 22nd.

Multiple other sites that use the API also report it, see:
https://www.rankedftw.com/ (at the top)
https://www.nephest.com/sc2/?#stats

**Comment by BurnySc2** [comment]
The fault was with me I suppose - they deprecated something in the API

https://us.forums.blizzard.com/en/blizzard/t/http-get-deprecated-for-oauthtoken-endpoint/15232

It should be working now again!
