### ISSUE TITLE
47 season MMR are broken

### ISSUE THREAD

**Issue by kalujny** [BurnySc2/MMR-Ranges#6]
League intervals are no longer mutually exclusive for EU

**Comment by BurnySc2** [comment]
Indeed, but there is nothing I can do because I pull the data directly from the Blizzard API. So something is wrong on Blizzard's end.

For the record:
![2021-04-07_18-13](https://user-images.githubusercontent.com/21288725/113899270-ebcaef80-97cc-11eb-983f-515cc5e4c9aa.png)

**Comment by BurnySc2** [comment]
New season started, so closing this issue.
