### ISSUE TITLE
MMR Ranges for Europe are broken

### ISSUE THREAD

**Issue by GalaxiousCosmo** [BurnySc2/MMR-Ranges#7]
MMR Ranges for Europe are not working outside of Grandmaster range, but Americas & Korea are working fine.
![image](https://github.com/BurnySc2/MMR-Ranges/assets/20133057/0b879ffb-8a41-48bc-aff0-95ece353bcc9)

**Comment by GalaxiousCosmo** [comment]
Just looked up and read other closed issues that it's due to Blizzard's API being unstable? That sucks then, typical Blizzard

**Comment by BurnySc2** [comment]
Closing this issue as the MMR ranges "work" again although there are still league overlaps.
