### ISSUE TITLE
Europe and Korea Ladder not working

### ISSUE THREAD

**Issue by Dziga-czj** [BurnySc2/MMR-Ranges#8]
Hey ! 
I put this issue, in case you haven't seen, we never know :)

**Comment by BurnySc2** [comment]
Thanks for opening the issue. 
I have seen the issue but nephest seems to have the same issue in grabbing/displaying the ranges:
https://sc2pulse.nephest.com/sc2/?season=60&queue=LOTV_1V1&team-type=ARRANGED&us=true&eu=true&kr=true&cn=true&bro=true&sil=true&gol=true&pla=true&dia=true&mas=true&gra=true&page=0&type=ladder&ratingAnchor=99999&idAnchor=0&count=1#stats-tier
![image](https://github.com/user-attachments/assets/4f54e643-8bca-42f3-a3a3-34d2f16e84b5)

I believe this is an issue with the SC2 API (although I haven't looked into it in detail) which should resolve itself on https://burnysc2.github.io/MMR-Ranges as soon as the API issue is fixed.
This issue arose when the season started which was roughly 5 weeks ago. Usually when there was an error, someone at blizzard would fix it in a few days/weeks but this time we need to be more patient as it seems. My guess is that it will resolve itself next season.

**Comment by Dziga-czj** [comment]
okay, thanks for answering ! 
thanks for keeping this leaderboard alive !
